"""
설정 다이얼로그 모듈

이 모듈은 애플리케이션의 전반적인 설정을 관리하는 다이얼로그를 제공합니다.
외관(테마, 색상), 수신 모델, 객체 관리, 신호 노이즈 설정 등을 포함합니다.

클래스:
    SettingsDialog: 설정 다이얼로그

주요 기능:
    - Appearance: 테마, 색상, 경로 두께 설정
    - Reception Model: 거리 기반 신호 수신 확률 모델 설정
    - Object: 자선 지정, 객체 목록 관리
    - Signal: 신호별 노이즈 레벨 및 AIS 프래그먼트 확률 설정
"""

from PyQt6.QtWidgets import (
    QDialog, QHBoxLayout, QListWidget, QFrame, QStackedWidget, QVBoxLayout,
    QDialogButtonBox, QWidget, QGroupBox, QFormLayout, QPushButton, QLabel,
    QCheckBox, QSpinBox, QComboBox, QTableWidget, QHeaderView, QTableWidgetItem,
    QDoubleSpinBox, QMessageBox, QColorDialog, QAbstractSpinBox, QTabWidget,
    QSlider, QScrollArea, QSizePolicy, QApplication
)
from PyQt6.QtCore import (
    Qt
)
from app.ui.styles import apply_modern_style

try:
    import pyqtgraph as pg
    PYQTGRAPH_AVAILABLE = True
except ImportError:
    PYQTGRAPH_AVAILABLE = False

import math
import numpy as np

from app.models.project import current_project
from app.models.settings import RECEPTION_PRESETS, ReceptionModelConfig


class SettingsDialog(QDialog):
    """
    애플리케이션 설정을 관리하는 다이얼로그 클래스입니다.

    좌측 목록에서 카테고리를 선택하면 우측에 해당 설정 페이지가 표시됩니다.

    카테고리:
        - Appearance: 외관 설정 (테마, 색상, 경로 두께)
        - Reception Model: 거리 기반 수신 확률 모델 (AIS, Radar, Camera)
        - Object: 자선 지정 및 객체 목록 관리
        - Signal: 신호 노이즈 및 AIS 프래그먼트 확률

    속성:
        list_widget: 카테고리 목록 위젯
        stack: 카테고리별 설정 페이지 스택
        reception_widgets: 수신 모델 설정 위젯 참조 딕셔너리
    """

    def __init__(self, parent=None):
        """
        SettingsDialog를 초기화합니다.

        매개변수:
            parent: 부모 위젯 (기본값: None)
        """
        super().__init__(parent)
        self.setWindowTitle("Settings")
        self.resize(1260, 728)
        
        main_h = QHBoxLayout(self)
        self.list_widget = QListWidget()
        self.list_widget.addItems(["Appearance", "Reception Model", "Object", "Signal", "Camera & Redis"])
        self.list_widget.setFixedWidth(150)
        
        line = QFrame()
        line.setFrameShape(QFrame.Shape.VLine)
        line.setFrameShadow(QFrame.Shadow.Sunken)
        
        self.stack = QStackedWidget()
        
        main_h.addWidget(self.list_widget)
        main_h.addWidget(line)
        main_h.addWidget(self.stack)
        
        self.init_appearance()
        self.init_dropout()
        self.init_object()
        self.init_signal()
        self.init_camera_redis()
        self._bind_sim_state()
        
        self.list_widget.currentRowChanged.connect(self.stack.setCurrentIndex)
        
        btn_layout = QVBoxLayout()
        bb = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok)
        bb.accepted.connect(self.accept)
        btn_layout.addStretch()
        btn_layout.addWidget(bb)
        main_h.addLayout(btn_layout)

    def init_appearance(self):
        """
        외관(Appearance) 설정 페이지를 초기화합니다.

        객체 색상, 경로 시각화, UI 테마 설정을 포함합니다.
        """
        w = QWidget()
        main_layout = QVBoxLayout(w)
        
        # --- Group 1: Object Colors ---
        grp_obj = QGroupBox("Object Colors")
        l_obj = QFormLayout(grp_obj)
        
        self.btn_own = QPushButton()
        self.btn_own.setFixedSize(25, 25)
        self.btn_own.setStyleSheet(f"background-color: {current_project.settings.own_color}")
        self.btn_own.clicked.connect(lambda: self.pick_color(self.btn_own, "own_color"))
        
        own_label = QLabel("Own Ship Color:")
        own_label.setToolTip("Set the color for Own Ship path and points.")
        l_obj.addRow(own_label, self.btn_own)

        self.btn_tgt = QPushButton()
        self.btn_tgt.setFixedSize(25, 25)
        self.btn_tgt.setStyleSheet(f"background-color: {current_project.settings.target_color}")
        self.btn_tgt.clicked.connect(lambda: self.pick_color(self.btn_tgt, "target_color"))
        
        tgt_label = QLabel("Target Ship Color:")
        tgt_label.setToolTip("Set the color for Target Ship path and points.")
        l_obj.addRow(tgt_label, self.btn_tgt)
        
        self.btn_rand_c = QPushButton()
        self.btn_rand_c.setFixedSize(25, 25)
        self.btn_rand_c.setStyleSheet(f"background-color: {current_project.settings.random_color}")
        self.btn_rand_c.clicked.connect(lambda: self.pick_color(self.btn_rand_c, "random_color"))
        
        rand_label = QLabel("Random Target Color:")
        rand_label.setToolTip("Set the color for Random Targets generated by RTG.")
        l_obj.addRow(rand_label, self.btn_rand_c)
        
        main_layout.addWidget(grp_obj)

        # --- Group 2: Path & Visualization ---
        grp_path = QGroupBox("Path & Visualization")
        l_path = QFormLayout(grp_path)
        
        self.chk_speed_notes = QCheckBox()
        speed_notes_label = QLabel("Show Speed Notes:")
        self.chk_speed_notes.setChecked(current_project.settings.show_speed_notes)
        
        self.spin_path_th = QSpinBox()
        self.spin_path_th.setRange(1, 10)
        self.spin_path_th.setValue(current_project.settings.path_thickness)
        
        self.spin_travel_th = QSpinBox()
        self.spin_travel_th.setRange(1, 10)
        self.spin_travel_th.setValue(current_project.settings.traveled_path_thickness)
        
        self.btn_high_c = QPushButton()
        self.btn_high_c.setFixedSize(25, 25)
        self.btn_high_c.setStyleSheet(f"background-color: {current_project.settings.highlight_path_color}")
        self.btn_high_c.clicked.connect(lambda: self.pick_color(self.btn_high_c, "highlight_path_color"))

        l_path.addRow(speed_notes_label, self.chk_speed_notes)
        l_path.addRow("진행 예정 경로 두께 (점선):", self.spin_path_th)
        l_path.addRow("진행 경로 두께:", self.spin_travel_th)
        l_path.addRow("강조(Highlight) 색상:", self.btn_high_c)
        
        main_layout.addWidget(grp_path)

        # --- Group 3: UI & Theme ---
        grp_ui = QGroupBox("UI & Theme")
        l_ui = QFormLayout(grp_ui)

        theme_label = QLabel("테마 (Theme):")
        self.combo_theme = QComboBox()
        self.combo_theme.addItems(["System", "Light", "Dark"])
        self.combo_theme.setCurrentText(current_project.settings.theme_mode)

        self.btn_sel = QPushButton()
        self.btn_sel.setFixedSize(25, 25)
        self.btn_sel.setStyleSheet(f"background-color: {current_project.settings.select_color}")
        self.btn_sel.clicked.connect(lambda: self.pick_color(self.btn_sel, "select_color"))
        
        sel_color_label = QLabel("Selection Color:")
        sel_color_label.setToolTip("Color used when an object or path is selected.")

        self.btn_mask = QPushButton()
        self.btn_mask.setFixedSize(25, 25)
        self.btn_mask.setStyleSheet(f"background-color: {current_project.settings.mask_color}")
        self.btn_mask.clicked.connect(lambda: self.pick_color(self.btn_mask, "mask_color"))
        
        mask_color_label = QLabel("Latitude Mask Color:")
        mask_color_label.setToolTip("Color to mask invalid latitude areas (> ±90 degrees).")

        l_ui.addRow(theme_label, self.combo_theme)
        l_ui.addRow(sel_color_label, self.btn_sel)
        l_ui.addRow(mask_color_label, self.btn_mask)
        
        main_layout.addWidget(grp_ui)
        main_layout.addStretch()
        
        self.stack.addWidget(w)

    def init_dropout(self):
        """
        수신 모델(Reception Model) 설정 페이지를 초기화합니다.

        거리 기반 신호 수신 확률 모델을 설정합니다.
        AIS, Radar, Camera 각각에 대해 독립적인 설정이 가능합니다.
        프리셋(Realistic, Stable, Harsh)을 제공하며 커스텀 설정도 가능합니다.
        """
        w = QWidget()
        main_layout = QVBoxLayout(w)

        # 상단: 전체 활성화 체크박스와 프리셋
        top_layout = QHBoxLayout()

        top_layout.addStretch()

        preset_label = QLabel("Preset:")
        top_layout.addWidget(preset_label)

        self.combo_preset = QComboBox()
        self.combo_preset.addItems(["Realistic (Default)", "Stable (Demo)", "Harsh (Stress)", "Custom"])
        preset_map = {"realistic": 0, "stable": 1, "harsh": 2, "custom": 3}
        self.combo_preset.setCurrentIndex(preset_map.get(current_project.settings.reception_preset, 0))
        self.combo_preset.currentIndexChanged.connect(self._on_preset_changed)
        top_layout.addWidget(self.combo_preset)

        self.btn_reset_preset = QPushButton("Reset to Preset")
        self.btn_reset_preset.clicked.connect(self._apply_preset)
        top_layout.addWidget(self.btn_reset_preset)

        main_layout.addLayout(top_layout)

        # 서브 탭 위젯
        self.reception_tabs = QTabWidget()

        # AIS 탭
        ais_tab = self._create_reception_tab("ais", current_project.settings.ais_reception)
        self.reception_tabs.addTab(ais_tab, "AIS")

        # Radar 탭
        radar_tab = self._create_reception_tab("radar", current_project.settings.radar_detect)
        self.reception_tabs.addTab(radar_tab, "Radar")

        # Camera 탭
        camera_tab = self._create_reception_tab("camera", current_project.settings.camera_reception)
        self.reception_tabs.addTab(camera_tab, "CAMERA")

        # Preview 탭

        main_layout.addWidget(self.reception_tabs)
        self.stack.addWidget(w)

    def _create_reception_tab(self, tab_type: str, config):
        """
        신호 타입별 수신 모델 설정 탭을 생성합니다.

        매개변수:
            tab_type: 신호 타입 ('ais', 'radar', 'camera')
            config: 현재 수신 모델 설정 객체

        반환값:
            QScrollArea: 생성된 탭 위젯

        설정 항목:
            - d0: 최대 신뢰 거리 (이 거리까지는 p0 확률 유지)
            - d1: 페이드아웃 종료 거리 (이 거리에서 p1 확률 도달)
            - p0: 근거리 드롭아웃 확률
            - p1: d1에서의 드롭아웃 확률
            - 곡선 타입: smoothstep, linear, logistic
            - 버스트 손실 설정
        """
        is_camera = (tab_type == "camera")

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)

        tab_widget = QWidget()
        layout = QVBoxLayout(tab_widget)

        # Simple Settings 그룹
        simple_group = QGroupBox("Simple Settings")
        simple_layout = QFormLayout(simple_group)

        # d0: Max reliable range
        spin_d0 = QDoubleSpinBox()
        spin_d0.setRange(0, 200)
        spin_d0.setSingleStep(1)
        spin_d0.setDecimals(1)
        spin_d0.setSuffix(" NM")
        spin_d0.setValue(config.d0)
        spin_d0.valueChanged.connect(lambda v: self._update_preview())
        simple_layout.addRow("Max reliable range (d0):", spin_d0)

        # d1: Fade-out end
        spin_d1 = QDoubleSpinBox()
        spin_d1.setRange(0, 200)
        spin_d1.setSingleStep(1)
        spin_d1.setDecimals(1)
        spin_d1.setSuffix(" NM")
        spin_d1.setValue(config.d1)
        spin_d1.valueChanged.connect(lambda v: self._update_preview())
        simple_layout.addRow("Fade-out end (d1):", spin_d1)

        # p0: Near-range dropout
        spin_p0 = QDoubleSpinBox()
        spin_p0.setRange(0, 1)
        spin_p0.setSingleStep(0.01)
        spin_p0.setDecimals(2)
        spin_p0.setValue(config.p0)
        spin_p0.valueChanged.connect(lambda v: self._update_preview())
        simple_layout.addRow("Near-range dropout (p0):", spin_p0)

        # p1: At d1 dropout
        spin_p1 = QDoubleSpinBox()
        spin_p1.setRange(0, 1)
        spin_p1.setSingleStep(0.01)
        spin_p1.setDecimals(2)
        # Camera: p1 is fixed at 1.0 and disabled
        if is_camera:
            spin_p1.setValue(1.0)
            spin_p1.setEnabled(False)
            spin_p1.setToolTip("CAMERA p1 is fixed at 1.0 (complete block at d1)")
        else:
            spin_p1.setValue(config.p1)
        spin_p1.valueChanged.connect(lambda v: self._update_preview())
        simple_layout.addRow("At d1 dropout (p1):", spin_p1)

        # Full block at d1
        chk_full_block = QCheckBox()
        # Camera: full_block_at_d1 is always ON and disabled
        if is_camera:
            chk_full_block.setChecked(True)
            chk_full_block.setEnabled(False)
            chk_full_block.setToolTip("CAMERA always blocks completely at d >= d1")
        else:
            chk_full_block.setChecked(config.full_block_at_d1)
        chk_full_block.stateChanged.connect(lambda v: self._update_preview())
        simple_layout.addRow("d >= d1 에서 완전 차단:", chk_full_block)

        layout.addWidget(simple_group)
        layout.addStretch()

        # 위젯 참조 저장
        if not hasattr(self, 'reception_widgets'):
            self.reception_widgets = {}
        widgets = {
            'd0': spin_d0, 'd1': spin_d1, 'p0': spin_p0, 'p1': spin_p1,
            'full_block': chk_full_block
        }
        self.reception_widgets[tab_type] = widgets

        scroll.setWidget(tab_widget)
        return scroll

    def _create_preview_tab(self):
        """
        Preview 탭을 생성합니다.

        pyqtgraph를 사용하여 거리에 따른 드롭아웃 확률을 시각화합니다.
        각 신호 타입별 확률 곡선과 현재 거리에서의 확률 값을 표시합니다.

        반환값:
            QWidget: 생성된 Preview 탭 위젯
        """
        tab_widget = QWidget()
        layout = QVBoxLayout(tab_widget)

        # 거리 슬라이더
        slider_layout = QHBoxLayout()
        slider_label = QLabel("Distance:")
        slider_layout.addWidget(slider_label)

        self.preview_slider = QSlider(Qt.Orientation.Horizontal)
        self.preview_slider.setRange(0, 60)
        self.preview_slider.setValue(30)
        self.preview_slider.valueChanged.connect(self._on_preview_slider_changed)
        slider_layout.addWidget(self.preview_slider)

        self.preview_dist_label = QLabel("30 NM")
        self.preview_dist_label.setMinimumWidth(60)
        slider_layout.addWidget(self.preview_dist_label)

        layout.addLayout(slider_layout)

        # pyqtgraph 그래프
        if PYQTGRAPH_AVAILABLE:
            self.preview_plot = pg.PlotWidget()
            self.preview_plot.setBackground('w')
            self.preview_plot.setLabel('left', 'Dropout Probability', units='%')
            self.preview_plot.setLabel('bottom', 'Distance', units='NM')
            self.preview_plot.setYRange(0, 100)
            self.preview_plot.setXRange(0, 60)
            self.preview_plot.addLegend()
            self.preview_plot.showGrid(x=True, y=True, alpha=0.3)

            # 플롯 라인
            self.plot_lines = {
                'ais': self.preview_plot.plot(pen=pg.mkPen('b', width=2), name='AIS'),
                'radar': self.preview_plot.plot(pen=pg.mkPen('g', width=2), name='Radar'),
                'camera': self.preview_plot.plot(pen=pg.mkPen('r', width=2), name='CAMERA'),
            }

            # 수직선 (현재 거리)
            self.preview_vline = pg.InfiniteLine(pos=30, angle=90, pen=pg.mkPen('k', width=1, style=Qt.PenStyle.DashLine))
            self.preview_plot.addItem(self.preview_vline)

            layout.addWidget(self.preview_plot)
        else:
            no_graph_label = QLabel("pyqtgraph not installed. Install with: pip install pyqtgraph")
            no_graph_label.setStyleSheet("color: red; font-style: italic;")
            layout.addWidget(no_graph_label)

        # 현재 거리에서의 확률 표시
        prob_group = QGroupBox("At Current Distance")
        prob_layout = QFormLayout(prob_group)

        self.prob_labels = {}
        for key, name in [('ais', 'P_drop(AIS)'), ('radar', 'P_drop(Radar)'),
                          ('camera', 'P_drop(CAMERA)')]:
            label = QLabel("0.0%")
            label.setMinimumWidth(80)
            prob_layout.addRow(f"{name}:", label)
            self.prob_labels[key] = label

        layout.addWidget(prob_group)

        return tab_widget

    def _calculate_dropout_prob(self, distance, config) -> float:
        """
        거리 기반 드롭아웃 확률을 계산합니다.

        매개변수:
            distance: 자선으로부터의 거리 (NM)
            config: 수신 모델 설정 객체

        반환값:
            float: 드롭아웃 확률 (0.0 ~ 1.0)

        계산 로직:
            - d <= d0: p0 반환 (근거리 고정 확률)
            - d >= d1: full_block이면 1.0, 아니면 p1 반환
            - d0 < d < d1: 곡선 타입에 따라 보간
        """
        d, d0, d1, p0, p1 = distance, config.d0, config.d1, config.p0, config.p1

        if d <= d0:
            return p0
        elif d >= d1:
            return 1.0 if config.full_block_at_d1 else p1
        else:
            t = (d - d0) / (d1 - d0) if (d1 - d0) > 0 else 0

            if config.curve_type == "linear":
                factor = t
            elif config.curve_type == "logistic":
                factor = 1 / (1 + math.exp(-10 * (t - 0.5)))
            else:  # smoothstep
                factor = t * t * (3 - 2 * t)

            return p0 + (p1 - p0) * factor

    def _get_current_config(self, tab_type: str):
        """
        현재 UI 값으로 수신 모델 설정 객체를 생성합니다.

        매개변수:
            tab_type: 신호 타입 ('ais', 'radar', 'camera')

        반환값:
            ReceptionModelConfig: 생성된 설정 객체
        """
        widgets = self.reception_widgets.get(tab_type, {})
        if not widgets:
            return None

        if tab_type == "ais":
            base_config = current_project.settings.ais_reception
        elif tab_type == "radar":
            base_config = current_project.settings.radar_detect
        elif tab_type == "camera":
            base_config = current_project.settings.camera_reception
        else:
            base_config = None
        curve_type = base_config.curve_type if base_config else "smoothstep"
        burst_enabled = base_config.burst_enabled if base_config else False
        burst_min_sec = base_config.burst_min_sec if base_config else 1.0
        burst_max_sec = base_config.burst_max_sec if base_config else 5.0
        burst_trigger_mult = base_config.burst_trigger_mult if base_config else 2.0

        config = ReceptionModelConfig(
            d0=widgets['d0'].value(),
            d1=widgets['d1'].value(),
            p0=widgets['p0'].value(),
            p1=widgets['p1'].value(),
            full_block_at_d1=widgets['full_block'].isChecked(),
            curve_type=curve_type,
            burst_enabled=burst_enabled,
            burst_min_sec=burst_min_sec,
            burst_max_sec=burst_max_sec,
            burst_trigger_mult=burst_trigger_mult
        )
        return config

    def _update_preview(self):
        """
        Preview 그래프를 업데이트합니다.

        모든 신호 타입의 드롭아웃 확률 곡선을 다시 그리고,
        현재 슬라이더 위치에서의 확률 값을 표시합니다.
        """
        if not PYQTGRAPH_AVAILABLE or not hasattr(self, 'preview_plot'):
            return

        distances = np.linspace(0, 60, 200)

        for tab_type in ['ais', 'radar', 'camera']:
            config = self._get_current_config(tab_type)
            if config:
                probs = [self._calculate_dropout_prob(d, config) * 100 for d in distances]
                self.plot_lines[tab_type].setData(distances, probs)

        # 현재 거리에서의 확률 업데이트
        current_dist = self.preview_slider.value()
        for tab_type in ['ais', 'radar', 'camera']:
            config = self._get_current_config(tab_type)
            if config:
                prob = self._calculate_dropout_prob(current_dist, config) * 100
                self.prob_labels[tab_type].setText(f"{prob:.1f}%")

    def _on_preview_slider_changed(self, value):
        """
        Preview 슬라이더 값 변경 시 호출됩니다.

        매개변수:
            value: 새 슬라이더 값 (거리, NM)
        """
        self.preview_dist_label.setText(f"{value} NM")
        if PYQTGRAPH_AVAILABLE and hasattr(self, 'preview_vline'):
            self.preview_vline.setPos(value)
        self._update_preview()
    def _on_preset_changed(self, index):
        """
        프리셋 콤보박스 변경 시 호출됩니다.

        현재는 자동 적용하지 않고 Reset 버튼을 통해 적용합니다.

        매개변수:
            index: 선택된 프리셋 인덱스
        """
        pass

    def _apply_preset(self):
        """
        선택된 프리셋을 모든 신호 타입에 적용합니다.

        프리셋 종류:
            - realistic: 현실적인 수신 환경
            - stable: 안정적인 데모 환경
            - harsh: 열악한 스트레스 테스트 환경
            - custom: 사용자 정의 (적용하지 않음)
        """
        preset_names = ["realistic", "stable", "harsh", "custom"]
        preset_name = preset_names[self.combo_preset.currentIndex()]

        if preset_name == "custom":
            return

        preset = RECEPTION_PRESETS.get(preset_name, {})

        # AIS
        if 'ais' in preset and 'ais' in self.reception_widgets:
            self._apply_preset_to_tab('ais', preset['ais'])

        # Radar
        if 'radar_detect' in preset and 'radar' in self.reception_widgets:
            self._apply_preset_to_tab('radar', preset['radar_detect'])

        # Camera
        if 'camera' in preset and 'camera' in self.reception_widgets:
            self._apply_preset_to_tab('camera', preset['camera'])

        self._update_preview()

    def _apply_preset_to_tab(self, tab_type: str, preset_data: dict):
        """
        프리셋 데이터를 특정 탭에 적용합니다.

        매개변수:
            tab_type: 신호 타입 ('ais', 'radar', 'camera')
            preset_data: 프리셋 설정 딕셔너리
        """
        widgets = self.reception_widgets.get(tab_type, {})
        if not widgets:
            return

        if 'd0' in preset_data:
            widgets['d0'].setValue(preset_data['d0'])
        if 'd1' in preset_data:
            widgets['d1'].setValue(preset_data['d1'])
        if 'p0' in preset_data:
            widgets['p0'].setValue(preset_data['p0'])
        if 'p1' in preset_data:
            widgets['p1'].setValue(preset_data['p1'])

    def init_object(self):
        """
        객체(Object) 설정 페이지를 초기화합니다.

        자선 인덱스 지정, 랜덤 타겟 설정, 객체 목록 관리 기능을 포함합니다.
        """
        w = QWidget()
        l = QVBoxLayout(w)
        
        own_ship_group = QGroupBox("Select Own Ship")
        form_layout = QFormLayout(own_ship_group)
        self.spin_own = QSpinBox()
        self.spin_own.setRange(0, 999)
        self.spin_own.setValue(current_project.settings.own_ship_idx)
        self.spin_own.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spin_own.setMaximumWidth(100)
        self._sync_own_ship_lock()
        label = QLabel("Own Ship Index:")
        label.setToolTip("Index (ID) of the ship to be treated as Own Ship. Own Ship generates additional signals like GPRMC.")
        form_layout.addRow(label, self.spin_own)
        l.addWidget(own_ship_group)

        # --- New: Random Target Settings ---
        random_target_group = QGroupBox("Random Target Settings")
        rtg_layout = QFormLayout(random_target_group)

        self.spin_speed_var = QDoubleSpinBox()
        self.spin_speed_var.setRange(0.0, 100.0)
        self.spin_speed_var.setSingleStep(0.1)
        self.spin_speed_var.setDecimals(2)
        self.spin_speed_var.setValue(current_project.settings.speed_variance)

        label_speed_var = QLabel("Speed Variance (kn^2):")
        label_speed_var.setToolTip("Unified variance for wind/current effects. Applied to RTG initial speed and simulation loop noise.")
        rtg_layout.addRow(label_speed_var, self.spin_speed_var)

        l.addWidget(random_target_group)
        # --- End New ---

        obj_group = QGroupBox("Object List")
        obj_layout = QVBoxLayout(obj_group)
        
        self.obj_table = QTableWidget()
        self.obj_table.setColumnCount(5)
        self.obj_table.setHorizontalHeaderLabels(["chk", "idx", "Type", "Name", "Generated"])
        self.obj_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.obj_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.obj_table.setColumnWidth(0, 40)
        self.obj_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
        self.obj_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.obj_table.verticalHeader().setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)

        all_objects = sorted(
            [(s.idx, "Ship", s) for s in current_project.ships] + 
            [(a.id, "Area", a) for a in current_project.areas], 
            key=lambda x: x[0]
        )
        
        self.obj_table.setRowCount(len(all_objects))

        for row, (obj_id, obj_type, obj_data) in enumerate(all_objects):
            chk_item = QTableWidgetItem()
            chk_item.setFlags(Qt.ItemFlag.ItemIsUserCheckable | Qt.ItemFlag.ItemIsEnabled)
            chk_item.setCheckState(Qt.CheckState.Unchecked)
            self.obj_table.setItem(row, 0, chk_item)

            idx_item = QTableWidgetItem(str(obj_id))
            idx_item.setFlags(idx_item.flags() & ~Qt.ItemFlag.ItemIsEditable)
            
            type_item = QTableWidgetItem(obj_type)
            type_item.setFlags(type_item.flags() & ~Qt.ItemFlag.ItemIsEditable)

            name_item = QTableWidgetItem(obj_data.name)
            if obj_type != "Ship":
                name_item.setFlags(name_item.flags() & ~Qt.ItemFlag.ItemIsEditable)

            gen_str = "-"
            if obj_type == "Ship":
                gen_str = "Yes" if obj_data.is_generated else "No"
            
            gen_item = QTableWidgetItem(gen_str)
            gen_item.setFlags(gen_item.flags() & ~Qt.ItemFlag.ItemIsEditable)
            if gen_str == "Yes": gen_item.setForeground(Qt.GlobalColor.green)

            self.obj_table.setItem(row, 1, idx_item)
            self.obj_table.setItem(row, 2, type_item)
            self.obj_table.setItem(row, 3, name_item)
            self.obj_table.setItem(row, 4, gen_item)

        obj_layout.addWidget(self.obj_table)
        
        self.btn_del_checked = QPushButton("Delete Checked Objects")
        self.btn_del_checked.clicked.connect(self.delete_checked_objects)
        obj_layout.addWidget(self.btn_del_checked)
        
        l.addWidget(obj_group)
        self.stack.addWidget(w)

    def _bind_sim_state(self):
        parent = self.parent()
        if parent and hasattr(parent, "sim_panel"):
            try:
                parent.sim_panel.state_changed.connect(self._sync_own_ship_lock)
            except Exception:
                pass

    def _is_simulation_active(self):
        parent = self.parent()
        if parent and hasattr(parent, "sim_panel"):
            sim_panel = parent.sim_panel
            worker = getattr(sim_panel, "worker", None)
            if worker and getattr(worker, "running", False):
                return True
        return False

    def _sync_own_ship_lock(self, *args):
        if hasattr(self, "spin_own"):
            self.spin_own.setEnabled(not self._is_simulation_active())
        
    def delete_checked_objects(self):
        """
        체크된 객체들을 삭제합니다.

        객체 목록에서 체크된 선박과 영역을 프로젝트에서 제거합니다.
        삭제 전 확인 대화상자를 표시합니다.
        """
        rows_to_del = []
        for row in range(self.obj_table.rowCount()):
            item = self.obj_table.item(row, 0)
            if item and item.checkState() == Qt.CheckState.Checked:
                rows_to_del.append(row)
        
        if not rows_to_del:
            QMessageBox.information(self, "Info", "No objects selected.")
            return

        if QMessageBox.question(self, "Delete Objects", f"Delete {len(rows_to_del)} objects?", 
                                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No) != QMessageBox.StandardButton.Yes:
            return

        # Get IDs to delete
        ids_to_del = [] # list of (id, type)
        for row in rows_to_del:
            oid = int(self.obj_table.item(row, 1).text())
            otype = self.obj_table.item(row, 2).text()
            ids_to_del.append((oid, otype))
            
        # Remove from project
        for oid, otype in ids_to_del:
            if otype == "Ship":
                current_project.ships = [s for s in current_project.ships if s.idx != oid]
            elif otype == "Area":
                current_project.areas = [a for a in current_project.areas if a.id != oid]
        
        # Remove from table (reverse order)
        for row in sorted(rows_to_del, reverse=True):
            self.obj_table.removeRow(row)
            
        QMessageBox.information(self, "Deleted", "Deleted.")

    def init_signal(self):
        """
        신호(Signal) 설정 페이지를 초기화합니다.

        AIS 프래그먼트 확률과 선박별 신호 노이즈 레벨을 설정합니다.
        """
        w = QWidget()
        layout = QVBoxLayout(w)

        # --- AIS Fragment Delivery Probability ---
        ais_frag_group = QGroupBox("AIS Fragment Settings")
        ais_frag_layout = QFormLayout(ais_frag_group)

        self.spin_fragment_delivery = QDoubleSpinBox()
        self.spin_fragment_delivery.setRange(0.0, 1.0)
        self.spin_fragment_delivery.setSingleStep(0.01)
        self.spin_fragment_delivery.setDecimals(2)
        self.spin_fragment_delivery.setValue(current_project.settings.ais_fragment_delivery_prob)

        delivery_label = QLabel("Fragment Delivery Probability:")
        ais_frag_layout.addRow(delivery_label, self.spin_fragment_delivery)

        layout.addWidget(ais_frag_group)
        # --- End AIS Fragment Settings ---
        self.stack.addWidget(w)

    def init_camera_redis(self):
        """
        카메라 및 Redis 설정 페이지를 초기화합니다.

        카메라 높이, EO/IR 카메라 활성화, Redis 전송 설정을 포함합니다.
        """
        w = QWidget()
        layout = QVBoxLayout(w)

        # --- Camera Settings Group ---
        camera_group = QGroupBox("Camera Settings")
        camera_layout = QFormLayout(camera_group)

        # 카메라 높이
        self.spin_camera_height = QDoubleSpinBox()
        self.spin_camera_height.setRange(1.0, 100.0)
        self.spin_camera_height.setSingleStep(1.0)
        self.spin_camera_height.setDecimals(1)
        self.spin_camera_height.setSuffix(" m")
        self.spin_camera_height.setValue(getattr(current_project.settings, 'camera_height_m', 15.0))
        height_label = QLabel("Camera Height (above deck):")
        height_label.setToolTip("Height of the camera mounted on Own Ship's deck.")
        camera_layout.addRow(height_label, self.spin_camera_height)

        # EO 카메라 활성화
        self.chk_eo_enabled = QCheckBox()
        self.chk_eo_enabled.setChecked(getattr(current_project.settings, 'eo_camera_enabled', True))
        eo_label = QLabel("EO Camera Enabled:")
        eo_label.setToolTip("EO Camera: 3840x1080 resolution, ±90° FOV")
        camera_layout.addRow(eo_label, self.chk_eo_enabled)

        # IR 카메라 활성화
        self.chk_ir_enabled = QCheckBox()
        self.chk_ir_enabled.setChecked(getattr(current_project.settings, 'ir_camera_enabled', True))
        ir_label = QLabel("IR Camera Enabled:")
        ir_label.setToolTip("IR Camera: 1536x512 resolution, ±55° FOV")
        camera_layout.addRow(ir_label, self.chk_ir_enabled)

        layout.addWidget(camera_group)

        # --- Redis Settings Group ---
        redis_group = QGroupBox("Redis Bbox Transmission")
        redis_layout = QFormLayout(redis_group)

        # Redis 활성화
        self.chk_redis_enabled = QCheckBox()
        self.chk_redis_enabled.setChecked(getattr(current_project.settings, 'redis_enabled', False))
        redis_enabled_label = QLabel("Enable Redis Transmission:")
        redis_enabled_label.setToolTip("Send bbox data to Redis server (infer:eo, infer:ir)")
        redis_layout.addRow(redis_enabled_label, self.chk_redis_enabled)

        # Redis Host 안내 (시뮬레이션 탭의 IP 사용)
        host_info_label = QLabel("Host: <i>Uses Simulation tab IP address</i>")
        host_info_label.setTextFormat(Qt.TextFormat.RichText)
        host_info_label.setToolTip("Redis host is automatically set to the IP address entered in the Simulation tab")
        redis_layout.addRow("", host_info_label)

        # Redis 포트
        self.spin_redis_port = QSpinBox()
        self.spin_redis_port.setRange(1, 65535)
        self.spin_redis_port.setValue(getattr(current_project.settings, 'redis_port', 6379))
        redis_port_label = QLabel("Redis Port:")
        redis_layout.addRow(redis_port_label, self.spin_redis_port)

        # Redis 비밀번호
        from PyQt6.QtWidgets import QLineEdit
        self.edit_redis_password = QLineEdit()
        self.edit_redis_password.setText(getattr(current_project.settings, 'redis_password', ''))
        self.edit_redis_password.setEchoMode(QLineEdit.EchoMode.Password)
        self.edit_redis_password.setPlaceholderText("(optional)")
        redis_password_label = QLabel("Redis Password:")
        redis_layout.addRow(redis_password_label, self.edit_redis_password)

        # Redis TLS
        self.chk_redis_tls = QCheckBox()
        self.chk_redis_tls.setChecked(getattr(current_project.settings, 'redis_use_tls', False))
        redis_tls_label = QLabel("Use TLS:")
        redis_layout.addRow(redis_tls_label, self.chk_redis_tls)

        layout.addWidget(redis_group)

        # Info label
        info_label = QLabel(
            "<b>Bbox Format:</b><br>"
            "Key: <code>infer:eo</code> / <code>infer:ir</code><br>"
            "Value: <code>{\"prediction\": [[left, top, right, bottom, conf, class], ...]}</code>"
        )
        info_label.setWordWrap(True)
        info_label.setTextFormat(Qt.TextFormat.RichText)
        layout.addWidget(info_label)

        layout.addStretch()
        self.stack.addWidget(w)

    def _test_redis_connection(self):
        """Redis 연결을 테스트합니다.

        Note: 실제 연결 시에는 시뮬레이션 탭의 IP가 사용됩니다.
        테스트는 localhost로 진행합니다.
        """
        try:
            import redis
            # 테스트는 localhost로 진행 (실제 연결 시 시뮬레이션 탭 IP 사용)
            host = '127.0.0.1'
            port = self.spin_redis_port.value()
            password = self.edit_redis_password.text() or None
            use_tls = self.chk_redis_tls.isChecked()

            if use_tls:
                client = redis.Redis(
                    host=host, port=port, password=password,
                    ssl=True, ssl_cert_reqs=None,
                    socket_connect_timeout=5.0
                )
            else:
                client = redis.Redis(
                    host=host, port=port, password=password,
                    socket_connect_timeout=5.0
                )

            client.ping()
            client.close()
            QMessageBox.information(
                self, "Success",
                f"Connected to Redis at {host}:{port}\n\n"
                "Note: During simulation, the IP from Simulation tab will be used."
            )
        except ImportError:
            QMessageBox.warning(self, "Error", "Redis module not installed.\nInstall with: pip install redis")
        except Exception as e:
            QMessageBox.warning(self, "Connection Failed", f"Failed to connect to Redis:\n{str(e)}")

    def pick_color(self, btn, attr):
        """
        색상 선택 다이얼로그를 표시하고 선택된 색상을 적용합니다.

        매개변수:
            btn: 색상을 표시할 버튼 위젯
            attr: 설정에 저장할 속성 이름
        """
        c = QColorDialog.getColor()
        if c.isValid():
            setattr(current_project.settings, attr, c.name())
            btn.setStyleSheet(f"background-color: {c.name()}")

    def apply_changes(self):
        """
        모든 설정 변경사항을 프로젝트에 적용합니다.

        각 설정 페이지의 UI 값을 읽어 current_project.settings에 저장합니다.
        테마 변경 시 즉시 적용됩니다.
        """
        for row in range(self.obj_table.rowCount()):
            obj_id = int(self.obj_table.item(row, 1).text())
            obj_type = self.obj_table.item(row, 2).text()
            
            new_name = self.obj_table.item(row, 3).text()

            if obj_type == "Ship":
                obj = current_project.get_ship_by_idx(obj_id)
                if obj:
                    obj.name = new_name
            elif obj_type == "Area":
                obj = current_project.get_area_by_id(obj_id)
                # Area name update if needed, but currently read-only in table logic above for non-ships

        current_project.settings.show_speed_notes = self.chk_speed_notes.isChecked()

        # Theme change - apply immediately
        new_theme = self.combo_theme.currentText()
        if new_theme != current_project.settings.theme_mode:
            current_project.settings.theme_mode = new_theme
            app = QApplication.instance()
            if app:
                apply_modern_style(app, new_theme)
        else:
            current_project.settings.theme_mode = new_theme

        current_project.settings.own_ship_idx = self.spin_own.value()
        current_project.settings.speed_variance = self.spin_speed_var.value()
        current_project.settings.path_thickness = self.spin_path_th.value()
        current_project.settings.traveled_path_thickness = self.spin_travel_th.value()

        # Reception Model 설정 저장
        preset_names = ["realistic", "stable", "harsh", "custom"]
        current_project.settings.reception_preset = preset_names[self.combo_preset.currentIndex()]

        # AIS reception config
        ais_config = self._get_current_config('ais')
        if ais_config:
            current_project.settings.ais_reception = ais_config

        # Radar detect config
        radar_config = self._get_current_config('radar')
        if radar_config:
            current_project.settings.radar_detect = radar_config

        # Camera reception config
        camera_config = self._get_current_config('camera')
        if camera_config:
            current_project.settings.camera_reception = camera_config

        current_project.settings.ais_fragment_delivery_prob = self.spin_fragment_delivery.value()

        # Camera & Redis 설정 저장
        current_project.settings.camera_height_m = self.spin_camera_height.value()
        current_project.settings.eo_camera_enabled = self.chk_eo_enabled.isChecked()
        current_project.settings.ir_camera_enabled = self.chk_ir_enabled.isChecked()
        current_project.settings.redis_enabled = self.chk_redis_enabled.isChecked()
        # redis_host는 시뮬레이션 탭의 IP를 사용하므로 여기서 저장하지 않음
        current_project.settings.redis_port = self.spin_redis_port.value()
        current_project.settings.redis_password = self.edit_redis_password.text()
        current_project.settings.redis_use_tls = self.chk_redis_tls.isChecked()

    def accept(self):
        """
        OK 버튼 클릭 시 변경사항을 적용하고 다이얼로그를 닫습니다.
        """
        self.apply_changes()
        super().accept()
