from PyQt6.QtWidgets import (
    QDialog, QHBoxLayout, QListWidget, QFrame, QStackedWidget, QVBoxLayout, 
    QDialogButtonBox, QWidget, QGroupBox, QFormLayout, QPushButton, QLabel, 
    QCheckBox, QSpinBox, QComboBox, QTableWidget, QHeaderView, QTableWidgetItem, 
    QDoubleSpinBox, QMessageBox, QColorDialog, QAbstractSpinBox
)
from PyQt6.QtCore import (
    Qt
)

from app.core.models.project import current_project

class SettingsDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Settings")
        self.resize(900, 520)
        
        main_h = QHBoxLayout(self)
        self.list_widget = QListWidget()
        self.list_widget.addItems(["Appearance", "Dropout", "Object", "Signal", "Simulation"])
        self.list_widget.setFixedWidth(150)
        
        line = QFrame()
        line.setFrameShape(QFrame.Shape.VLine)
        line.setFrameShadow(QFrame.Shadow.Sunken)
        
        self.stack = QStackedWidget()
        
        main_h.addWidget(self.list_widget)
        main_h.addWidget(line)
        main_h.addWidget(self.stack)
        
        self.init_appearance()
        self.init_dropout()
        self.init_object()
        self.init_signal()
        self.init_simulation()
        
        self.list_widget.currentRowChanged.connect(self.stack.setCurrentIndex)
        
        btn_layout = QVBoxLayout()
        bb = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok)
        bb.accepted.connect(self.accept)
        btn_layout.addStretch()
        btn_layout.addWidget(bb)
        main_h.addLayout(btn_layout)

    def init_appearance(self):
        w = QWidget()
        main_layout = QVBoxLayout(w)
        
        # --- Group 1: Object Colors ---
        grp_obj = QGroupBox("Object Colors")
        l_obj = QFormLayout(grp_obj)
        
        self.btn_own = QPushButton()
        self.btn_own.setFixedSize(25, 25)
        self.btn_own.setStyleSheet(f"background-color: {current_project.settings.own_color}")
        self.btn_own.clicked.connect(lambda: self.pick_color(self.btn_own, "own_color"))
        
        own_label = QLabel("Own Ship Color:")
        own_label.setToolTip("Set the color for Own Ship path and points.")
        l_obj.addRow(own_label, self.btn_own)

        self.btn_tgt = QPushButton()
        self.btn_tgt.setFixedSize(25, 25)
        self.btn_tgt.setStyleSheet(f"background-color: {current_project.settings.target_color}")
        self.btn_tgt.clicked.connect(lambda: self.pick_color(self.btn_tgt, "target_color"))
        
        tgt_label = QLabel("Target Ship Color:")
        tgt_label.setToolTip("Set the color for Target Ship path and points.")
        l_obj.addRow(tgt_label, self.btn_tgt)
        
        self.btn_rand_c = QPushButton()
        self.btn_rand_c.setFixedSize(25, 25)
        self.btn_rand_c.setStyleSheet(f"background-color: {current_project.settings.random_color}")
        self.btn_rand_c.clicked.connect(lambda: self.pick_color(self.btn_rand_c, "random_color"))
        
        rand_label = QLabel("Random Target Color:")
        rand_label.setToolTip("Set the color for Random Targets generated by RTG.")
        l_obj.addRow(rand_label, self.btn_rand_c)
        
        main_layout.addWidget(grp_obj)

        # --- Group 2: Path & Visualization ---
        grp_path = QGroupBox("Path & Visualization")
        l_path = QFormLayout(grp_path)
        
        self.chk_speed_notes = QCheckBox()
        speed_notes_label = QLabel("Show Speed Notes:")
        self.chk_speed_notes.setChecked(current_project.settings.show_speed_notes)
        
        self.spin_path_th = QSpinBox()
        self.spin_path_th.setRange(1, 10)
        self.spin_path_th.setValue(current_project.settings.path_thickness)
        
        self.spin_travel_th = QSpinBox()
        self.spin_travel_th.setRange(1, 10)
        self.spin_travel_th.setValue(current_project.settings.traveled_path_thickness)
        
        self.btn_high_c = QPushButton()
        self.btn_high_c.setFixedSize(25, 25)
        self.btn_high_c.setStyleSheet(f"background-color: {current_project.settings.highlight_path_color}")
        self.btn_high_c.clicked.connect(lambda: self.pick_color(self.btn_high_c, "highlight_path_color"))

        l_path.addRow(speed_notes_label, self.chk_speed_notes)
        l_path.addRow("진행 예정 경로 두께 (점선):", self.spin_path_th)
        l_path.addRow("진행 경로 두께:", self.spin_travel_th)
        l_path.addRow("강조(Highlight) 색상:", self.btn_high_c)
        
        main_layout.addWidget(grp_path)

        # --- Group 3: UI & Theme ---
        grp_ui = QGroupBox("UI & Theme")
        l_ui = QFormLayout(grp_ui)

        theme_label = QLabel("테마 (Theme):")
        self.combo_theme = QComboBox()
        self.combo_theme.addItems(["System", "Light", "Dark"])
        self.combo_theme.setCurrentText(current_project.settings.theme_mode)

        self.btn_sel = QPushButton()
        self.btn_sel.setFixedSize(25, 25)
        self.btn_sel.setStyleSheet(f"background-color: {current_project.settings.select_color}")
        self.btn_sel.clicked.connect(lambda: self.pick_color(self.btn_sel, "select_color"))
        
        sel_color_label = QLabel("Selection Color:")
        sel_color_label.setToolTip("Color used when an object or path is selected.")

        self.btn_mask = QPushButton()
        self.btn_mask.setFixedSize(25, 25)
        self.btn_mask.setStyleSheet(f"background-color: {current_project.settings.mask_color}")
        self.btn_mask.clicked.connect(lambda: self.pick_color(self.btn_mask, "mask_color"))
        
        mask_color_label = QLabel("Latitude Mask Color:")
        mask_color_label.setToolTip("Color to mask invalid latitude areas (> ±90 degrees).")

        l_ui.addRow(theme_label, self.combo_theme)
        l_ui.addRow(sel_color_label, self.btn_sel)
        l_ui.addRow(mask_color_label, self.btn_mask)
        
        main_layout.addWidget(grp_ui)
        main_layout.addStretch()
        
        self.stack.addWidget(w)

    def init_dropout(self):
        w = QWidget()
        l = QFormLayout(w)
        self.drop_spins = {}
        for key in [
            "AIVDM", "RATTM", "Camera"]:
            s = QDoubleSpinBox()
            s.setRange(0, 1)
            s.setSingleStep(0.01)
            s.setValue(current_project.settings.dropout_probs.get(key, 0.1))
            
            label = QLabel(f"{key} Dropout Probability:")
            label.setToolTip(f"Probability that {key} signal is lost (0.0=No loss, 1.0=Always lost).")
            l.addRow(label, s)
            self.drop_spins[key] = s
        self.stack.addWidget(w)

    def init_object(self):
        w = QWidget()
        l = QVBoxLayout(w)
        
        own_ship_group = QGroupBox("Select Own Ship")
        form_layout = QFormLayout(own_ship_group)
        self.spin_own = QSpinBox()
        self.spin_own.setRange(0, 999)
        self.spin_own.setValue(current_project.settings.own_ship_idx)
        self.spin_own.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spin_own.setMaximumWidth(100)
        label = QLabel("Own Ship Index:")
        label.setToolTip("Index (ID) of the ship to be treated as Own Ship. Own Ship generates additional signals like GPRMC.")
        form_layout.addRow(label, self.spin_own)
        l.addWidget(own_ship_group)

        # --- New: Random Target Settings ---
        random_target_group = QGroupBox("Random Target Settings")
        rtg_layout = QFormLayout(random_target_group)

        self.spin_speed_var = QDoubleSpinBox()
        self.spin_speed_var.setRange(0.0, 100.0)
        self.spin_speed_var.setSingleStep(0.1)
        self.spin_speed_var.setDecimals(2)
        self.spin_speed_var.setValue(current_project.settings.speed_variance)

        label_speed_var = QLabel("Speed Variance (kn^2):")
        label_speed_var.setToolTip("Unified variance for wind/current effects. Applied to RTG initial speed and simulation loop noise.")
        rtg_layout.addRow(label_speed_var, self.spin_speed_var)

        l.addWidget(random_target_group)
        # --- End New ---

        obj_group = QGroupBox("Object List")
        obj_layout = QVBoxLayout(obj_group)
        
        self.obj_table = QTableWidget()
        self.obj_table.setColumnCount(5)
        self.obj_table.setHorizontalHeaderLabels(["chk", "idx", "Type", "Name", "Generated"])
        self.obj_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.obj_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.obj_table.setColumnWidth(0, 40)
        self.obj_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
        self.obj_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.obj_table.verticalHeader().setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)

        all_objects = sorted(
            [(s.idx, "Ship", s) for s in current_project.ships] + 
            [(a.id, "Area", a) for a in current_project.areas], 
            key=lambda x: x[0]
        )
        
        self.obj_table.setRowCount(len(all_objects))

        for row, (obj_id, obj_type, obj_data) in enumerate(all_objects):
            chk_item = QTableWidgetItem()
            chk_item.setFlags(Qt.ItemFlag.ItemIsUserCheckable | Qt.ItemFlag.ItemIsEnabled)
            chk_item.setCheckState(Qt.CheckState.Unchecked)
            self.obj_table.setItem(row, 0, chk_item)

            idx_item = QTableWidgetItem(str(obj_id))
            idx_item.setFlags(idx_item.flags() & ~Qt.ItemFlag.ItemIsEditable)
            
            type_item = QTableWidgetItem(obj_type)
            type_item.setFlags(type_item.flags() & ~Qt.ItemFlag.ItemIsEditable)

            name_item = QTableWidgetItem(obj_data.name)
            if obj_type != "Ship":
                name_item.setFlags(name_item.flags() & ~Qt.ItemFlag.ItemIsEditable)

            gen_str = "-"
            if obj_type == "Ship":
                gen_str = "Yes" if obj_data.is_generated else "No"
            
            gen_item = QTableWidgetItem(gen_str)
            gen_item.setFlags(gen_item.flags() & ~Qt.ItemFlag.ItemIsEditable)
            if gen_str == "Yes": gen_item.setForeground(Qt.GlobalColor.green)

            self.obj_table.setItem(row, 1, idx_item)
            self.obj_table.setItem(row, 2, type_item)
            self.obj_table.setItem(row, 3, name_item)
            self.obj_table.setItem(row, 4, gen_item)

        obj_layout.addWidget(self.obj_table)
        
        self.btn_del_checked = QPushButton("Delete Checked Objects")
        self.btn_del_checked.clicked.connect(self.delete_checked_objects)
        obj_layout.addWidget(self.btn_del_checked)
        
        l.addWidget(obj_group)
        self.stack.addWidget(w)
        
    def delete_checked_objects(self):
        rows_to_del = []
        for row in range(self.obj_table.rowCount()):
            item = self.obj_table.item(row, 0)
            if item and item.checkState() == Qt.CheckState.Checked:
                rows_to_del.append(row)
        
        if not rows_to_del:
            QMessageBox.information(self, "Info", "No objects selected.")
            return

        if QMessageBox.question(self, "Delete Objects", f"Delete {len(rows_to_del)} objects?", 
                                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No) != QMessageBox.StandardButton.Yes:
            return

        # Get IDs to delete
        ids_to_del = [] # list of (id, type)
        for row in rows_to_del:
            oid = int(self.obj_table.item(row, 1).text())
            otype = self.obj_table.item(row, 2).text()
            ids_to_del.append((oid, otype))
            
        # Remove from project
        for oid, otype in ids_to_del:
            if otype == "Ship":
                current_project.ships = [s for s in current_project.ships if s.idx != oid]
            elif otype == "Area":
                current_project.areas = [a for a in current_project.areas if a.id != oid]
        
        # Remove from table (reverse order)
        for row in sorted(rows_to_del, reverse=True):
            self.obj_table.removeRow(row)
            
        QMessageBox.information(self, "Deleted", "Deleted.")

    def init_signal(self):
        w = QWidget()
        layout = QVBoxLayout(w)
        
        info_label = QLabel("Set noise levels for each signal type.")
        info_label.setToolTip("Set small fluctuations (noise) for each ship and signal type to increase realism.")
        info_label.setStyleSheet("font-style: italic; color: #555;")
        layout.addWidget(info_label)

        # --- New: AIS Fragment Probabilities ---
        ais_frag_group = QGroupBox("AIS Message Fragment Probabilities (1-5 fragments)")
        ais_frag_layout = QFormLayout(ais_frag_group)

        self.ais_frag_spins = []
        for i in range(5):
            s = QDoubleSpinBox()
            s.setRange(0.0, 100.0) # Probabilities can be relative, so a wider range
            s.setSingleStep(0.1)
            s.setDecimals(2)
            s.setValue(current_project.settings.ais_fragment_probs[i])
            
            label = QLabel(f"{i+1} Fragment Probability:")
            label.setToolTip(f"Relative probability of generating an AIS message with {i+1} fragments.")
            ais_frag_layout.addRow(label, s)
            self.ais_frag_spins.append(s)
        
        layout.addWidget(ais_frag_group)
        # --- End New ---

        self.signal_noise_table = QTableWidget()
        self.talkers = ["AIVDM", "RATTM", "Camera"]
        ships = current_project.ships
        
        self.signal_noise_table.setRowCount(len(ships) + 1)
        self.signal_noise_table.setColumnCount(len(self.talkers) + 1)

        self.signal_noise_table.setHorizontalHeaderLabels(["Ctrl"] + self.talkers)
        self.signal_noise_table.setVerticalHeaderLabels(["ALL"] + [s.name for s in ships])

        for r in range(self.signal_noise_table.rowCount()):
            for c in range(self.signal_noise_table.columnCount()):
                val = 0.001
                if r > 0 and c > 0:
                    ship = ships[r - 1]
                    talker = self.talkers[c - 1]
                    val = ship.variances.get(talker, 0.001)

                spin = self._create_signal_noise_cell(val)
                spin.setProperty("row", r)
                spin.setProperty("col", c)
                spin.valueChanged.connect(self.on_signal_noise_changed)
                self.signal_noise_table.setCellWidget(r, c, spin)

        self.signal_noise_table.verticalHeader().setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)
        self.signal_noise_table.setColumnWidth(0, 40)
        self.signal_noise_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        for i in range(1, self.signal_noise_table.columnCount()):
            self.signal_noise_table.horizontalHeader().setSectionResizeMode(i, QHeaderView.ResizeMode.Stretch)
        
        layout.addWidget(self.signal_noise_table)
        self.stack.addWidget(w)

    def init_simulation(self):
        w = QWidget()
        l = QFormLayout(w)
        
        self.chk_zigzag = QCheckBox()
        self.chk_zigzag.setChecked(current_project.settings.rtg_zigzag_enabled)
        l.addRow("Enable RTG Zigzag Maneuver:", self.chk_zigzag)
        
        self.spin_zigzag_turns = QSpinBox()
        self.spin_zigzag_turns.setRange(1, 10)
        self.spin_zigzag_turns.setValue(current_project.settings.rtg_zigzag_turns)
        l.addRow("RTG Zigzag Turns (Expected Value):", self.spin_zigzag_turns)
        
        self.spin_zigzag_angle = QDoubleSpinBox()
        self.spin_zigzag_angle.setRange(0, 180)
        self.spin_zigzag_angle.setValue(current_project.settings.rtg_zigzag_angle_limit)
        self.spin_zigzag_angle.setSuffix(" deg")
        l.addRow("RTG Zigzag Angle Limit (+/-):", self.spin_zigzag_angle)
        
        self.stack.addWidget(w)

    def _create_signal_noise_cell(self, value):
        spin = QDoubleSpinBox()
        spin.setRange(0, 1.0)
        spin.setSingleStep(0.001)
        spin.setDecimals(5)
        spin.setValue(value)
        spin.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        spin.lineEdit().setAlignment(Qt.AlignmentFlag.AlignCenter)
        return spin

    def on_signal_noise_changed(self, value):
        sender_spin = self.sender()
        if not sender_spin: return

        r = sender_spin.property("row")
        c = sender_spin.property("col")

        table = self.signal_noise_table
        ships = current_project.ships

        rows_model = [r] if r > 0 else range(1, len(ships) + 1)
        cols_model = [c] if c > 0 else range(1, len(self.talkers) + 1)
        if r == 0 and c == 0:
            rows_model = range(1, len(ships) + 1)
            cols_model = range(1, len(self.talkers) + 1)

        for row_idx in rows_model:
            for col_idx in cols_model:
                ship = ships[row_idx - 1]
                talker = self.talkers[col_idx - 1]
                ship.variances[talker] = value

        if r == 0 or c == 0:
            rows_ui = range(table.rowCount()) if r == 0 else [r]
            cols_ui = range(table.columnCount()) if c == 0 else [c]
            if r == 0 and c == 0:
                rows_ui = range(table.rowCount())
                cols_ui = range(table.columnCount())

            for row in rows_ui:
                for col in cols_ui:
                    if row == r and col == c: continue
                    self._set_signal_noise_spinbox(row, col, value)
    
    def _set_signal_noise_spinbox(self, r, c, value):
        widget = self.signal_noise_table.cellWidget(r, c)
        if widget and isinstance(widget, QDoubleSpinBox):
            widget.blockSignals(True)
            widget.setValue(value)
            widget.blockSignals(False)

    def pick_color(self, btn, attr):
        c = QColorDialog.getColor()
        if c.isValid():
            setattr(current_project.settings, attr, c.name())
            btn.setStyleSheet(f"background-color: {c.name()}")

    def apply_changes(self):
        for row in range(self.obj_table.rowCount()):
            obj_id = int(self.obj_table.item(row, 1).text())
            obj_type = self.obj_table.item(row, 2).text()
            
            new_name = self.obj_table.item(row, 3).text()

            if obj_type == "Ship":
                obj = current_project.get_ship_by_idx(obj_id)
                if obj:
                    obj.name = new_name
            elif obj_type == "Area":
                obj = current_project.get_area_by_id(obj_id)
                # Area name update if needed, but currently read-only in table logic above for non-ships

        current_project.settings.show_speed_notes = self.chk_speed_notes.isChecked()
        current_project.settings.theme_mode = self.combo_theme.currentText()
        current_project.settings.own_ship_idx = self.spin_own.value()
        current_project.settings.speed_variance = self.spin_speed_var.value()
        current_project.settings.path_thickness = self.spin_path_th.value()
        current_project.settings.traveled_path_thickness = self.spin_travel_th.value()
        for k, s in self.drop_spins.items():
            current_project.settings.dropout_probs[k] = s.value()
        
        for i, s in enumerate(self.ais_frag_spins):
            current_project.settings.ais_fragment_probs[i] = s.value()
            
        current_project.settings.rtg_zigzag_enabled = self.chk_zigzag.isChecked()
        current_project.settings.rtg_zigzag_turns = self.spin_zigzag_turns.value()
        current_project.settings.rtg_zigzag_angle_limit = self.spin_zigzag_angle.value()
